### ISSUE TITLE
Undefined method error in generating Task Definition

### ISSUE THREAD

**Issue by LarsDR** [tongueroo/ufo#35]
Hi!

My setup might be a bit atypical, so I'm sorry if it's "out of scope", but after updating to the latest version, I'm no longer able to ship my services. I'm getting the following error:

```
Building Task Definitions...
Generating Task Definitions:
Traceback (most recent call last):
	17: from /usr/local/var/rbenv/versions/2.5.0/bin/ufo:23:in `<main>'
	16: from /usr/local/var/rbenv/versions/2.5.0/bin/ufo:23:in `load'
	15: from /usr/local/var/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ufo-3.5.1/exe/ufo:14:in `<top (required)>'
	14: from /usr/local/var/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	13: from /usr/local/var/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ufo-3.5.1/lib/ufo/command.rb:43:in `dispatch'
	12: from /usr/local/var/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	11: from /usr/local/var/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	10: from /usr/local/var/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	 9: from /usr/local/var/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ufo-3.5.1/lib/ufo/cli.rb:53:in `ship'
	 8: from /usr/local/var/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ufo-3.5.1/lib/ufo/tasks/builder.rb:8:in `ship'
	 7: from /usr/local/var/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ufo-3.5.1/lib/ufo/tasks/builder.rb:20:in `build'
	 6: from /usr/local/var/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ufo-3.5.1/lib/ufo/dsl.rb:18:in `run'
	 5: from /usr/local/var/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ufo-3.5.1/lib/ufo/dsl.rb:67:in `build_task_definitions'
	 4: from /usr/local/var/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ufo-3.5.1/lib/ufo/dsl.rb:67:in `each'
	 3: from /usr/local/var/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ufo-3.5.1/lib/ufo/dsl.rb:68:in `block in build_task_definitions'
	 2: from /usr/local/var/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ufo-3.5.1/lib/ufo/dsl/task_definition.rb:25:in `build'
	 1: from /usr/local/var/rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ufo-3.5.1/lib/ufo/dsl/task_definition.rb:25:in `instance_eval'
./.ufo/task_definitions.rb:20:in `block in evaluate_template_definitions': undefined method `+' for nil:NilClass (NoMethodError)
```

My ufo files are like the following:

**task_definitions.rb**
```
task_definition "services-static-images-tsen" do
  source "main" # will use ufo/templates/main.json.erb
  variables(
    family: task_definition_name,
    name: task_definition_name,
    container_port: helper.dockerfile_port,
    environment: @environment + @tsen_environment,
    domain: @tsen_domain,
    awslogs_group: "ecs/tsen/services/static/images",
    awslogs_stream_prefix: @environment_name,
    awslogs_region: helper.current_region,
  )
end
```
**base.rb**
```
@image = helper.full_image_name # includes the git sha tongueroo/hi:ufo-[sha].
@cpu = 0
@memory_reservation = 128
@environment = [
	{name: "AWS_ACCESS_KEY", value: "XXX"},
	{name: "AWS_REGION", value: "XXX"},
	{name: "AWS_SECRET_KEY", value: "XXX"},
  ]
```

**development.rb**
```
# Example ufo/variables/development.rb
# More info on how variables work: http://ufoships.com/docs/variables/
@environment = @environment + helper.env_vars(%Q[
  ASPNETCORE_ENVIRONMENT=Development
])

@tsen_environment = [
  {name: "AWS_S3_BUCKET_NAME", value: "XXX"},
  {name: "SENTRY_DSN", value: "XXX"}
]

@tsen_domain = "api.example.com"
@environment_name = "staging"
```

My bet would be, that it has something to do with the environment concatenations. I'll try to narrow it down to figure out, where the error happens.

**Comment by LarsDR** [comment]
Just tested with version `3.3.1`, and it works. With `3.4.4` it doesn't work.

**Comment by tongueroo** [comment]
@LarsDR oops just saw this. Can you try v3.5.x In 3.4.x notice a similar error and fixed it in 3.5.x. Let me know how it goes.

**Comment by tongueroo** [comment]
@LarsDR Nevermind, reproduced this on ufo 3.5.x. Thanks for the example files, they're very helpful. Will look into this bug.

**Comment by tongueroo** [comment]
@LarsDR This was a result of unintended consequence when I refactored in 3.4.x and starting controlling template scope more sanely. Allowed usage of shared variables in the task_definition blocks again 👍  Thanks for reporting.

Release fix in v3.5.3 https://github.com/tongueroo/ufo/blob/master/CHANGELOG.md 

Code diff is here https://github.com/tongueroo/ufo/pull/36/files if you're interested.
