### ISSUE TITLE
deploying production error: did not find expected key while parsing a block mapping

### ISSUE THREAD

**Issue by eni9889** [tongueroo/ufo#61]
When I deploy the default development cluster it works fine but when I set `UFO_ENV=production` I get the following error:

```
Creating stack production-logistics-app-web...
Traceback (most recent call last):
	28: from /Users/egjoka/.rbenv/versions/2.5.1/bin/ufo:23:in `<main>'
	27: from /Users/egjoka/.rbenv/versions/2.5.1/bin/ufo:23:in `load'
	26: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ufo-4.1.10/exe/ufo:14:in `<top (required)>'
	25: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	24: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ufo-4.1.10/lib/ufo/command.rb:43:in `dispatch'
	23: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	22: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	21: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	20: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ufo-4.1.10/lib/ufo/cli.rb:94:in `ships'
	19: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ufo-4.1.10/lib/ufo/cli.rb:94:in `each_with_index'
	18: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ufo-4.1.10/lib/ufo/cli.rb:94:in `each'
	17: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ufo-4.1.10/lib/ufo/cli.rb:99:in `block in ships'
	16: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ufo-4.1.10/lib/ufo/ship.rb:28:in `deploy'
	15: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ufo-4.1.10/lib/ufo/ship.rb:65:in `deploy_stack'
	14: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ufo-4.1.10/lib/ufo/stack.rb:52:in `deploy'
	13: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ufo-4.1.10/lib/ufo/stack.rb:67:in `perform'
	12: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ufo-4.1.10/lib/ufo/stack.rb:85:in `stack_options'
	11: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ufo-4.1.10/lib/ufo/stack.rb:170:in `save_template'
	10: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ufo-4.1.10/lib/ufo/stack.rb:81:in `template_body'
	 9: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/memoist-0.11.0/lib/memoist.rb:130:in `scope'
	 8: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ufo-4.1.10/lib/ufo/stack/context.rb:31:in `scope'
	 7: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/memoist-0.11.0/lib/memoist.rb:130:in `cfn'
	 6: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ufo-4.1.10/lib/ufo/stack/context.rb:250:in `cfn'
	 5: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/memoist-0.11.0/lib/memoist.rb:130:in `data'
	 4: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/ufo-4.1.10/lib/ufo/setting/profile.rb:20:in `data'
	 3: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/2.5.0/psych.rb:263:in `load'
	 2: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/2.5.0/psych.rb:350:in `parse'
	 1: from /Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/2.5.0/psych.rb:402:in `parse_stream'
/Users/egjoka/.rbenv/versions/2.5.1/lib/ruby/2.5.0/psych.rb:402:in `parse': (<unknown>): did not find expected key while parsing a block mapping at line 6 column 1 (Psych::SyntaxError)
```

**Comment by eni9889** [comment]
Sorry seems this was due to a malformed YAML file.

**Comment by tongueroo** [comment]
Yup, created a quick demo project for a list of yaml files to debug:

    $ find .ufo -name *.yml
    .ufo/params.yml
    .ufo/settings/cfn/default.yml
    .ufo/settings/network/default.yml
    .ufo/settings.yml
    $

Here's a dirty loop to check the yaml sytax on the files for all the files in the `.ufo` folder for posterity.

    for i in $(find .ufo -name *.yml); do echo $i ; ruby -ryaml -rjson -e "YAML.load_file('$i')" ; done
    
It would be nice if ufo provided a friendly error messsage to the user though. Hopefully someone has some time to take a look. Happy to take this PR! 😁 Thanks for the report.
